language: node_js
node_js:
  - "7"
dist: trusty # needs Ubuntu Trusty
sudo: required  # no need for virtualization.
addons:
  chrome: stable # have Travis install chrome stable.
#before_script:
#    - "sudo chown root /opt/google/chrome/chrome-sandbox"
#    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn test
